version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      # Add other environment variables as needed
    volumes:
      - ./:/app
      - /app/node_modules
    # Uncomment the following lines if you're using a database
    # depends_on:
    #  - database

  # Example PostgreSQL database service
  # database:
  #   image: postgres:15-alpine
  #   container_name: fastify-postgres
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=fastify_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# Uncomment if using a database service
# volumes:
#   postgres_data:
